probes:
  - id: https://namb.ch/api/admin/login
    requests:
      - method: POST
        url: https://namb.ch/api/admin/login
        headers:
          content-length: '46'
          pragma: no-cache
          cache-control: no-cache
          sec-ch-ua: '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"'
          sec-ch-ua-mobile: '?0'
          upgrade-insecure-requests: '1'
          origin: https://namb.ch
          content-type: application/x-www-form-urlencoded
          user-agent: >-
            Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
            (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
          accept: >-
            text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
          sec-fetch-site: same-origin
          sec-fetch-mode: navigate
          sec-fetch-user: '?1'
          sec-fetch-dest: document
          referer: https://namb.ch/admin
          accept-encoding: gzip, deflate, br
          accept-language: en-GB,en-US;q=0.9,en;q=0.8
          cookie: >-
            _fbp=fb.1.1624520390835.1717829411; _gid=GA825140508.1627380527;
            _gat_gtag_UA_89898_8=1; _ga_AAAAA=GS1.1.1.26.1.1.0; _ga=1.1
        params: {}
        body: email=myemail&password=mypass
notifications:
  - id: default
    type: desktop
