probes:
  - id: https://monika.hyperjump.tech
    name: https://monika.hyperjump.tech
    requests:
      - url: https://monika.hyperjump.tech
        method: GET
        timeout: 10000
        body: {}
    interval: 900
    alerts:
      - assertion: response.status < 200 or response.status > 299
        message: HTTP Status is not 200
      - assertion: response.time > 2000
        message: Response time is more than 2000ms
  - id: https://github.com
    name: https://github.com
    requests:
      - url: https://github.com
        method: GET
        timeout: 10000
        body: {}
    interval: 900
    alerts:
      - assertion: response.status < 200 or response.status > 299
        message: HTTP Status is not 200
      - assertion: response.time > 2000
        message: Response time is more than 2000ms
notifications:
  - id: default
    type: desktop
